apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  annotations:
  labels:
    app: guestbook-ui
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: guestbook-ui
